### ISSUE TITLE
Blocked updates when using router and styletron plugins

### ISSUE THREAD

**Issue by KevinGrandon** [fusionjs/fusion-plugin-styletron-react#112]
### Type of issue

Bug

### Description

Including the fusion-plugin-styletron-react plugin will block react router updates occasionally.

### Current behavior

I'm still working on a STR here, but it seems that including fusion-plugin-styletron-react will cause the router plugin to stop working. Links can be clicked which will update the browser URL, but the component does not render.

It feels like a symptom of: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

### Expected behavior

Everything works as normal.

### Your environment

I'll try to implement a minimal reproducible repository.

### Interesting note:

This reproduces with code like:
```js
app.register(Styletron);
app.register(Router);
```

If you simply swap the order, the issue goes away:
```js
app.register(Router);
app.register(Styletron);
```

**Comment by rtsao** [comment]
Should be resolved in React 16.4
https://github.com/facebook/react/issues/12551
