### ISSUE TITLE
Unable to use Styletron components in a standard Fusion app

### ISSUE THREAD

**Issue by jasonbarone** [fusionjs/fusion-plugin-styletron-react#142]
### Type of issue

Bug

### Description

Receiving the following error when importing a Styletron-built component to a FusionJS app:
```
Error: A Styletron styled component was rendered, but no Styletron engine instance was provided in React context. Did you forget to provide a Styletron engine instance to React context via using the Styletron provider component? Note: Providers and Consumers must come from the exact same React.createContext call to work. If your app has multiple instances of the "styletron-react-core" package in your node_module tree, your Provider may be coming from a different React.createContext call, which means the styled components will not recieve the provided engine instance. This scenario can arise, for example, when using "npm link".
```

### Current behavior

Fusion app crashes with error when using component.

### Expected behavior

Fusion app should be able to use Styletron components.

### Steps to reproduce

1. Scaffold a new Fusion app using CLI.
2. Import a component that uses styletron as dependency.

### Your environment

* fusion-plugin-styletron-react version: 2.5.0

* Node.js version (`node --version`): 8.11.3

* npm version (`npm --version`): 5.6.0

* Operating System: Mac 10.13.6

**Comment by jasonbarone** [comment]
This issue was due to including styletron-react as a dependency in the imported components, instead of a peerDep.

**Comment by zirho** [comment]
I have a one question regarding this.
Can I make it work with my package via 'npm link' or 'yarn link'.
